# Generated by Django 3.2.11 on 2022-01-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomreservation_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='chair_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
