# Generated by Django 3.2.11 on 2022-01-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomreservation_chair_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomreservation',
            name='chair_number',
        ),
    ]
